In [1]:
#Data Analytics-project-1
#Data cleaning & preparation
import pandas as pd
file_path=r"C:\Users\ANJALI SHAW\Downloads\Dataset for Data Analytics - Sheet1.csv"
df = pd.read_csv(file_path)
print("Dataset loaded successfully!")

Dataset loaded successfully!

In [2]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [3]:
df.shape

(1200, 14)

In [4]:
df.columns.tolist()

['OrderID',
 'Date',
 'CustomerID',
 'Product',
 'Quantity',
 'UnitPrice',
 'ShippingAddress',
 'PaymentMethod',
 'OrderStatus',
 'TrackingNumber',
 'ItemsInCart',
 'CouponCode',
 'ReferralSource',
 'TotalPrice']

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [6]:
df.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [ ]:
## 1. Initial Data Audit

The first step is to inspect the raw dataset before making
any modifications. This includes checking the dataset size,
column names, missing values, duplicate records, and data types.

In [7]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Rows: 1200
Columns: 14

Columns:
['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

Data Types:
OrderID             object
Date                object
CustomerID          object
Product             object
Quantity             int64
UnitPrice          float64
ShippingAddress     object
PaymentMethod       object
OrderStatus         object
TrackingNumber      object
ItemsInCart          int64
CouponCode          object
ReferralSource      object
TotalPrice         float64
dtype: object

In [8]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

display(missing_report)

                 Missing_Count  Missing_Percentage
OrderID                      0                0.00
Date                         0                0.00
CustomerID                   0                0.00
Product                      0                0.00
Quantity                     0                0.00
UnitPrice                    0                0.00
ShippingAddress              0                0.00
PaymentMethod                0                0.00
OrderStatus                  0                0.00
TrackingNumber               0                0.00
ItemsInCart                  0                0.00
CouponCode                 309               25.75
ReferralSource               0                0.00
TotalPrice                   0                0.00

In [9]:
df["CouponCode"] = df["CouponCode"].fillna("No Coupon")

In [10]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [11]:
df["Date"].head(20)

0     2023-01-04
1     2024-08-23
2     2024-02-27
3     2023-10-15
4     2025-05-08
5     2023-10-23
6     2025-06-17
7     2023-05-12
8     2025-04-02
9     2023-11-21
10    2023-12-29
11    2024-02-17
12    2024-10-15
13    2023-08-30
14    2023-03-27
15    2023-07-17
16    2023-01-24
17    2024-03-02
18    2025-03-26
19    2023-01-23
Name: Date, dtype: object

In [12]:
#Data cleaning
#check original data type
df["Date"].dtype

dtype('O')

In [13]:
#convert date to datetime
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [14]:
#check data type after conversion
print(df["Date"].dtype)

datetime64[ns]

In [15]:
#check invalid /missing dates
print("Missing/Invalid dates:", df["Date"].isna().sum())

Missing/Invalid dates: 0

In [16]:
#check date range
print("Earliest date:", df["Date"].min())
print("Latest date:", df["Date"].max())

Earliest date: 2023-01-01 00:00:00
Latest date: 2025-06-30 00:00:00

In [17]:
print(df["Date"].head(20))

0    2023-01-04
1    2024-08-23
2    2024-02-27
3    2023-10-15
4    2025-05-08
5    2023-10-23
6    2025-06-17
7    2023-05-12
8    2025-04-02
9    2023-11-21
10   2023-12-29
11   2024-02-17
12   2024-10-15
13   2023-08-30
14   2023-03-27
15   2023-07-17
16   2023-01-24
17   2024-03-02
18   2025-03-26
19   2023-01-23
Name: Date, dtype: datetime64[ns]

In [18]:
# Check missing values in every column

missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

display(missing_report)

                 Missing_Count  Missing_Percentage
OrderID                      0                 0.0
Date                         0                 0.0
CustomerID                   0                 0.0
Product                      0                 0.0
Quantity                     0                 0.0
UnitPrice                    0                 0.0
ShippingAddress              0                 0.0
PaymentMethod                0                 0.0
OrderStatus                  0                 0.0
TrackingNumber               0                 0.0
ItemsInCart                  0                 0.0
CouponCode                   0                 0.0
ReferralSource               0                 0.0
TotalPrice                   0                 0.0

In [19]:
#check duplicate rows
duplicate_count = df.duplicated().sum()

print("Total duplicate rows:", duplicate_count)

Total duplicate rows: 0

In [20]:
duplicate_order_ids = df["OrderID"].duplicated().sum()

print("Duplicate OrderIDs:", duplicate_order_ids)

Duplicate OrderIDs: 0

In [22]:
numeric_columns = [
    "Quantity",
    "UnitPrice",
    "ItemsInCart",
    "TotalPrice"
]

print(numeric_columns)

['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']

In [23]:
df[numeric_columns].dtypes

Quantity         int64
UnitPrice      float64
ItemsInCart      int64
TotalPrice     float64
dtype: object

In [24]:
display(df[numeric_columns].describe())

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [25]:
for column in numeric_columns:
    print(f"\n{column} - Negative values:")
    display(df[df[column] < 0])

Quantity - Negative values:

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

UnitPrice - Negative values:

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

ItemsInCart - Negative values:

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

TotalPrice - Negative values:

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice]
Index: []

In [26]:
print(df[numeric_columns].dtypes)

Quantity         int64
UnitPrice      float64
ItemsInCart      int64
TotalPrice     float64
dtype: object

In [27]:
display(df[numeric_columns].describe())

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

In [28]:
df["CalculatedTotal"] = df["Quantity"] * df["UnitPrice"]

df["PriceDifference"] = (
    df["TotalPrice"] - df["CalculatedTotal"]
)

print(
    "Mismatched TotalPrice:",
    (df["PriceDifference"].abs() > 0.01).sum()
)

Mismatched TotalPrice: 0

In [29]:
df.drop(
    columns=["CalculatedTotal", "PriceDifference"],
    inplace=True
)

In [30]:
print(df.columns.tolist())

['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice', 'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber', 'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice']

In [31]:
text_columns = [
    "Product",
    "ShippingAddress",
    "PaymentMethod",
    "OrderStatus",
    "TrackingNumber",
    "CouponCode",
    "ReferralSource"
]

for column in text_columns:
    extra_spaces = (
        df[column].astype(str) !=
        df[column].astype(str).str.strip()
    ).sum()

    print(f"{column}: {extra_spaces} values with extra spaces")

Product: 0 values with extra spaces
ShippingAddress: 0 values with extra spaces
PaymentMethod: 0 values with extra spaces
OrderStatus: 0 values with extra spaces
TrackingNumber: 0 values with extra spaces
CouponCode: 0 values with extra spaces
ReferralSource: 0 values with extra spaces

In [32]:
print(df["PaymentMethod"].value_counts())
print(df["OrderStatus"].value_counts())
print(df["ReferralSource"].value_counts())
for column in text_columns:
    extra_spaces = (
        df[column].astype(str) !=
        df[column].astype(str).str.strip()
    ).sum()

    print(f"{column}: {extra_spaces}")

PaymentMethod
Online         258
Cash           246
Credit Card    234
Debit Card     232
Gift Card      230
Name: count, dtype: int64
OrderStatus
Cancelled    250
Returned     247
Pending      237
Shipped      235
Delivered    231
Name: count, dtype: int64
ReferralSource
Instagram    259
Email        250
Google       241
Facebook     228
Referral     222
Name: count, dtype: int64
Product: 0
ShippingAddress: 0
PaymentMethod: 0
OrderStatus: 0
TrackingNumber: 0
CouponCode: 0
ReferralSource: 0

In [33]:
print("Unique OrderIDs:", df["OrderID"].nunique())
print("Unique CustomerIDs:", df["CustomerID"].nunique())
print("Unique TrackingNumbers:", df["TrackingNumber"].nunique())

Unique OrderIDs: 1200
Unique CustomerIDs: 1189
Unique TrackingNumbers: 1200

In [34]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [35]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate OrderIDs:", df["OrderID"].duplicated().sum())

Duplicate rows: 0
Duplicate OrderIDs: 0

In [36]:
print("Invalid/Missing dates:", df["Date"].isna().sum())
print("Date data type:", df["Date"].dtype)

Invalid/Missing dates: 0
Date data type: datetime64[ns]

In [37]:
print("========== FINAL DATASET ==========")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nData Types:")
print(df.dtypes)

========== FINAL DATASET ==========
Rows: 1200
Columns: 14

Data Types:
OrderID                    object
Date               datetime64[ns]
CustomerID                 object
Product                    object
Quantity                    int64
UnitPrice                 float64
ShippingAddress            object
PaymentMethod              object
OrderStatus                object
TrackingNumber             object
ItemsInCart                 int64
CouponCode                 object
ReferralSource             object
TotalPrice                float64
dtype: object

In [38]:
display(df.head(10))

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
5,ORD200005,2023-10-23,C37249,Phone,2,245.86,934 Main St,Credit Card,Shipped,TRK72976927,4,SAVE10,Instagram,491.72
6,ORD200006,2025-06-17,C83492,Laptop,1,664.42,986 Main St,Gift Card,Returned,TRK96417362,6,SAVE10,Facebook,664.42
7,ORD200007,2023-05-12,C41460,Monitor,5,149.55,706 Main St,Cash,Shipped,TRK78809193,9,FREESHIP,Facebook,747.75
8,ORD200008,2025-04-02,C26817,Phone,2,134.28,904 Main St,Gift Card,Cancelled,TRK61042692,2,No Coupon,Email,268.56
9,ORD200009,2023-11-21,C31946,Desk,4,509.38,102 Main St,Credit Card,Shipped,TRK33478363,6,SAVE10,Google,2037.52

In [39]:
cleaning_summary = pd.DataFrame({
    "Check": [
        "Missing Values",
        "Duplicate Rows",
        "Duplicate OrderIDs",
        "Invalid Dates",
        "Negative Quantity",
        "Negative UnitPrice",
        "Negative ItemsInCart",
        "Negative TotalPrice",
        "TotalPrice Mismatch",
        "Extra Whitespace"
    ],
    "Result": [
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df["OrderID"].duplicated().sum(),
        df["Date"].isna().sum(),
        (df["Quantity"] < 0).sum(),
        (df["UnitPrice"] < 0).sum(),
        (df["ItemsInCart"] < 0).sum(),
        (df["TotalPrice"] < 0).sum(),
        0,
        0
    ]
})

display(cleaning_summary)

                  Check  Result
0        Missing Values       0
1        Duplicate Rows       0
2    Duplicate OrderIDs       0
3         Invalid Dates       0
4     Negative Quantity       0
5    Negative UnitPrice       0
6  Negative ItemsInCart       0
7   Negative TotalPrice       0
8   TotalPrice Mismatch       0
9      Extra Whitespace       0

In [40]:
output_path = r"C:\Users\ANJALI SHAW\Downloads\cleaned_dataset.csv"

df.to_csv(
    output_path,
    index=False
)

print("Cleaned dataset saved successfully!")
print(output_path)

Cleaned dataset saved successfully!
C:\Users\ANJALI SHAW\Downloads\cleaned_dataset.csv

In [41]:
cleaned_df = pd.read_csv(output_path)

print("Saved dataset shape:", cleaned_df.shape)

display(cleaned_df.head())

Saved dataset shape: (1200, 14)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [42]:
change_log = pd.DataFrame({
    "Change_ID": [
        "CR001"
    ],
    "Column": [
        "Date"
    ],
    "Issue": [
        "Date values were stored as object/text"
    ],
    "Action": [
        "Converted Date column to datetime format"
    ],
    "Impact": [
        "Dates can now be reliably analyzed and validated"
    ],
    "Status": [
        "Resolved"
    ]
})

display(change_log)

,Change_ID,Column,Issue,Action,Impact,Status
0,CR001,Date,Date values were stored as object/text,Converted Date column to datetime format,Dates can now be reliably analyzed and validated,Resolved

In [43]:
change_log_path = r"C:\Users\ANJALI SHAW\Downloads\change_log.csv"

change_log.to_csv(
    change_log_path,
    index=False
)

print("Change log saved successfully!")

Change log saved successfully!

In [44]:
print("===================================")
print("       FINAL QUALITY REPORT")
print("===================================")

print("Total Records:", len(df))
print("Total Columns:", len(df.columns))

print("\nMissing Values:",
      df.isnull().sum().sum())

print("Duplicate Rows:",
      df.duplicated().sum())

print("Duplicate OrderIDs:",
      df["OrderID"].duplicated().sum())

print("Invalid Dates:",
      df["Date"].isna().sum())

print("Negative Quantity:",
      (df["Quantity"] < 0).sum())

print("Negative UnitPrice:",
      (df["UnitPrice"] < 0).sum())

print("Negative ItemsInCart:",
      (df["ItemsInCart"] < 0).sum())

print("Negative TotalPrice:",
      (df["TotalPrice"] < 0).sum())

print("===================================")

===================================
       FINAL QUALITY REPORT
===================================
Total Records: 1200
Total Columns: 14

Missing Values: 0
Duplicate Rows: 0
Duplicate OrderIDs: 0
Invalid Dates: 0
Negative Quantity: 0
Negative UnitPrice: 0
Negative ItemsInCart: 0
Negative TotalPrice: 0
===================================

In [48]:
cleaned_path = r"C:\Users\ANJALI SHAW\Downloads\cleaned_dataset.csv"

cleaned_df = pd.read_csv(cleaned_path)

print("Cleaned CSV loaded successfully!")
print("Shape:", cleaned_df.shape)

display(cleaned_df.head())

Cleaned CSV loaded successfully!
Shape: (1200, 14)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04